version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    command: ['npm', 'run', 'test']
